# Generated by Django 5.1 on 2024-09-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_seat_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('bus_number', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
